fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reinitialisation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

the_fireflies_user:
    resource: "@TheFirefliesUserBundle/Resources/config/routing.yml"
    prefix:   /

the_fireflies_sport:
    resource: "@TheFirefliesSportBundle/Resources/config/routing.yml"
    prefix:   /

